databases:
  - name: micronaut
    databaseName: micronaut_v7ox
    user: micronaut_v7ox_user 

services:
  - type: web
    name: expense-planner
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false